apiVersion: apps/v1
kind: Deployment
metadata:
  name: qiniu-deployment
spec:
  selector:
    matchLabels:
      app: qiniu
  replicas: 1
  template:
    metadata:
      labels:
        app: qiniu
    spec:
      containers:
      - name: qiniu
        image: registry.cn-shanghai.aliyuncs.com/ecnupet/qiniu:v0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: qiniu-app-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: qiniu

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: qiniu-app-vs
spec:
  hosts: #virtual service的hosts字段与Gateway的servers.hosts字段需要匹配
  - "ecnu.space" 
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /api/qiniu
    route:
    - destination:
        port:
          number: 8000
        host: qiniu-app-svc